[package]
name = "app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
linked_list = { path = "/home/cesar/Projects/Rust/algorithms/Linked-List/linked_list" }